### ISSUE TITLE
Error while installing climt

### ISSUE THREAD

**Issue by rvalenzuelar** [CliMT/climt#117]
* CliMT version: 0.16.3
* Python version: 3.6.9
* Operating System: MacOS Mojave

### Description

I was trying to install Climt. I got an error. I expected to install Climt.

### What I Did

- Cloned climt from Github
- make new conda environment
- installed python 3.6
- run pip install -r requirements_dev.txt
- run python setup.py install

Got the following traceback:
```
Compilers:  gcc-6 gfortran-6
running install
running bdist_egg
running egg_info
writing climt.egg-info/PKG-INFO
writing dependency_links to climt.egg-info/dependency_links.txt
writing requirements to climt.egg-info/requires.txt
writing top-level names to climt.egg-info/top_level.txt
reading manifest file 'climt.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.so' under directory 'climt'
warning: no files found matching '*.dylib' under directory 'climt'
warning: no files found matching '*.pyd' under directory 'climt'
no previously-included directories found matching 'climt/_lib/lib'
no previously-included directories found matching 'climt/_lib/share'
no previously-included directories found matching 'climt/_lib/include'
no previously-included directories found matching 'climt/_lib/bin'
no previously-included directories found matching 'climt/_lib/fftw*'
no previously-included directories found matching 'climt/_lib/shtns*'
warning: no previously-included files found matching 'climt/_lib/.configured*'
warning: no previously-included files matching '*.pyc' found under directory 'climt'
warning: no previously-included files matching '*.mod' found under directory 'climt'
warning: no previously-included files matching '*.o' found under directory 'climt'
warning: no previously-included files matching '*.c' found under directory 'climt'
warning: no previously-included files matching '__pycache__' found under directory '*'
no previously-included directories found matching 'tests/__pycache__'
warning: no files found matching '*.gif' under directory 'docs'
writing manifest file 'climt.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build/lib.macosx-10.7-x86_64-3.6
creating build/lib.macosx-10.7-x86_64-3.6/climt
copying climt/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components
copying climt/_components/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components
copying climt/_components/_berger_solar_insolation.pyx -> build/lib.macosx-10.7-x86_64-3.6/climt/_components
copying climt/_components/berger_solar_insolation.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components
copying climt/_components/grid_scale_condensation.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components
copying climt/_components/held_suarez.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components
copying climt/_components/radiation.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components
copying climt/_components/slab_surface.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components
copying climt/_components/surface_ice.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/dcmip
copying climt/_components/dcmip/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/dcmip
copying climt/_components/dcmip/_dcmip.pyx -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/dcmip
copying climt/_components/dcmip/component.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/dcmip
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/dry_convection
copying climt/_components/dry_convection/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/dry_convection
copying climt/_components/dry_convection/component.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/dry_convection
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/emanuel
copying climt/_components/emanuel/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/emanuel
copying climt/_components/emanuel/_emanuel_convection.pyx -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/emanuel
copying climt/_components/emanuel/component.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/emanuel
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/gfs
copying climt/_components/gfs/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/gfs
copying climt/_components/gfs/_gfs_dynamics.pyx -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/gfs
copying climt/_components/gfs/component.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/gfs
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/instellation
copying climt/_components/instellation/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/instellation
copying climt/_components/instellation/component.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/instellation
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg
copying climt/_components/rrtmg/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg
copying climt/_components/rrtmg/rrtmg_common.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg/lw
copying climt/_components/rrtmg/lw/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg/lw
copying climt/_components/rrtmg/lw/_rrtmg_lw.pyx -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg/lw
copying climt/_components/rrtmg/lw/component.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg/lw
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg/sw
copying climt/_components/rrtmg/sw/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg/sw
copying climt/_components/rrtmg/sw/_rrtmg_sw.pyx -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg/sw
copying climt/_components/rrtmg/sw/component.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/rrtmg/sw
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/second_best
copying climt/_components/second_best/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/second_best
creating build/lib.macosx-10.7-x86_64-3.6/climt/_components/simple_physics
copying climt/_components/simple_physics/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/simple_physics
copying climt/_components/simple_physics/_simple_physics.pyx -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/simple_physics
copying climt/_components/simple_physics/component.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_components/simple_physics
creating build/lib.macosx-10.7-x86_64-3.6/climt/_core
copying climt/_core/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_core
copying climt/_core/constants.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_core
copying climt/_core/initialization.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_core
copying climt/_core/util.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_core
creating build/lib.macosx-10.7-x86_64-3.6/climt/_data
copying climt/_data/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_data
copying climt/_data/ozone_profile.npy -> build/lib.macosx-10.7-x86_64-3.6/climt/_data
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib
copying climt/_lib/Makefile -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib
copying climt/_lib/OpenBLAS-0.2.19.tar.gz -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib
copying climt/_lib/fftw-3.3.6-pl2.tar.gz -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib
copying climt/_lib/shtns-2.7-r557.tar.gz -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib/Darwin
copying climt/_lib/Darwin/.temp -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/Darwin
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/Makefile -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/Makefile.conf -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/Makefile.conf.gfortran -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/Makefile.conf.ifort -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/driver.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/dyn_finalize.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/dyn_init.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/dyn_run.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/finalize.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/gfs_namelist -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/grid_data.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/init.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/kinds.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/params.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/phy_data.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/phy_finalize.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/phy_init.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/phy_run.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/phy_run_stub.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/physcons.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/pressure_data.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/run.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/semimp_data.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/shtns.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
copying climt/_lib/GFS/spectral_data.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/GFS
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib/Linux
copying climt/_lib/Linux/.temp -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/Linux
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib/Windows
copying climt/_lib/Windows/.temp -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/Windows
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib/dcmip
copying climt/_lib/dcmip/Makefile -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/dcmip
copying climt/_lib/dcmip/dcmip_initial_conditions_test_1_2_3_v5.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/dcmip
copying climt/_lib/dcmip/dcmip_initial_conditions_test_4_v3.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/dcmip
copying climt/_lib/dcmip/dcmip_initial_conditions_test_5_v1.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/dcmip
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib/emanuel
copying climt/_lib/emanuel/Makefile -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/emanuel
copying climt/_lib/emanuel/convect43c.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/emanuel
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/Makefile -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/mcica_random_numbers.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/mcica_subcol_gen_lw.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/parkind.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/parrrtm.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_cld.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_con.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg01.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg02.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg03.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg04.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg05.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg06.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg07.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg08.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg09.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg10.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg11.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg12.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg13.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg14.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg15.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_kg16.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_ncpar.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_ref.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_tbl.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_vsn.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrlw_wvn.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_c_binder.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_cldprmc.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_cldprop.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_init.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_k_g.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_rad.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_rad.nomcica.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_read_nc.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_rtrn.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_rtrnmc.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_rtrnmr.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_setcoef.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/rrtmg_lw_taumol.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
copying climt/_lib/rrtmg_lw/setup.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_lw
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/Makefile -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/README -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/mcica_random_numbers.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/mcica_subcol_gen_sw.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/parkind.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/parrrsw.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_aer.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_cld.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_con.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg16.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg17.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg18.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg19.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg20.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg21.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg22.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg23.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg24.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg25.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg26.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg27.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg28.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_kg29.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_ncpar.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_ref.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_tbl.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_vsn.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrsw_wvn.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_c_binder.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_cldprmc.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_cldprop.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_init.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_k_g.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_rad.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_rad.nomcica.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_reftra.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_setcoef.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_spcvmc.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_spcvrt.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_taumol.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/rrtmg_sw_vrtqdr.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
copying climt/_lib/rrtmg_sw/setup.py -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/rrtmg_sw
creating build/lib.macosx-10.7-x86_64-3.6/climt/_lib/simple_physics
copying climt/_lib/simple_physics/Makefile -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/simple_physics
copying climt/_lib/simple_physics/simple_physics_custom.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/simple_physics
copying climt/_lib/simple_physics/simple_physics_v5_1.f90 -> build/lib.macosx-10.7-x86_64-3.6/climt/_lib/simple_physics
running build_ext
if [ ! -d OpenBLAS-0.2.19 ]; then tar -xvzf OpenBLAS-0.2.19.tar.gz > log 2>&1; fi; cd OpenBLAS-0.2.19; CFLAGS="-I/Users/raulvalenzuela/Github/climt/climt/_lib -L/Users/raulvalenzuela/Github/climt/climt/_lib/Darwin/ -fPIC -O3 -mmacosx-version-min=10.7" make NO_SHARED=1 NO_LAPACK=0 > log 2>&1 ; make PREFIX=/Users/raulvalenzuela/Github/climt/climt/_lib NO_SHARED=1 NO_LAPACK=0 install > log.install.blas 2>&1 ; cp ../lib/libopenblas.a /Users/raulvalenzuela/Github/climt/climt/_lib/Darwin/
cp: ../lib/libopenblas.a: No such file or directory
make: *** [Darwin/libopenblas.a] Error 1
Traceback (most recent call last):
  File "setup.py", line 285, in <module>
    tests_require=test_requirements
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/raulvalenzuela/miniconda2/envs/climt2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 168, in run
    build_libraries()
  File "setup.py", line 159, in build_libraries
    raise RuntimeError('Library build failed, exiting')
RuntimeError: Library build failed, exiting
```

**Comment by JoyMonteiro** [comment]
Hello Raul,

any reason you need to install from source? There is a binary wheel available for Mac (climt 0.16.3). could you see if

```
pip install climt==0.16.3
```

works for you?

There have been [other people with issues](https://github.com/CliMT/climt/issues/116) building climt on Mac as well, which is why I recommend using the binary unless you want to change some Fortran-level code.

**Comment by rvalenzuelar** [comment]
Hi Joy,
I tried with pip also but I got a similar error in this section:
```
if [ ! -d OpenBLAS-0.2.19 ]; then tar -xvzf OpenBLAS-0.2.19.tar.gz > log 2>&1; fi; cd OpenBLAS-0.2.19; CFLAGS="-I/Users/raulvalenzuela/Github/climt/climt/_lib -L/Users/raulvalenzuela/Github/climt/climt/_lib/Darwin/ -fPIC -O3 -mmacosx-version-min=10.7" make NO_SHARED=1 NO_LAPACK=0 > log 2>&1 ; make PREFIX=/Users/raulvalenzuela/Github/climt/climt/_lib NO_SHARED=1 NO_LAPACK=0 install > log.install.blas 2>&1 ; cp ../lib/libopenblas.a /Users/raulvalenzuela/Github/climt/climt/_lib/Darwin/
cp: ../lib/libopenblas.a: No such file or directory
make: *** [Darwin/libopenblas.a] Error 1
```

**Comment by JoyMonteiro** [comment]
Hello Raul,

this should be because you tried
```
pip install climt
```
which tries to install the latest 0.16.9 version. Due to Travis acting unpredictably, I have disabled
travis Mac builds since 0.16.3 (I intend to resume Mac builds using Azure pipelines in the coming month or so).

Therefore, you could try and see if
```
pip install climt==0.16.3
```

works, since this version has a prebuilt binary for Mac. See https://pypi.org/project/climt/0.16.3/#files

**Comment by JoyMonteiro** [comment]
If you tried install 0.16.3 and pip decided to use a source install for some reason (it should not for Mojave), then the reasons for failure will be present in the openblas directory (climt/_lib/openblas/)

it should be a file called `log` and/or `log.install.blas`.

**Comment by rvalenzuelar** [comment]
Ok, I successfully installed climt. I made a new environment with python=3.6 and then run
```
pip install climt==0.16.3
```
Probably the issue was due to python 2.7?

**Comment by JoyMonteiro** [comment]
Great! Yes, we do not support binary builds for py27 on Mac, since most users use the anaconda distribution.

**Comment by JoyMonteiro** [comment]
I just uploaded climt wheels for 0.16.9 for Mac. hopefully now you should be able to install the
latest version!
